apiVersion: v1
kind: ConfigMap
metadata:
  name: execution-service-config
  namespace: codeview
data:
  NODE_ENV:    "production"
  PORT:        "5001"
  LOG_FORMAT:  "json"
  SERVICE_NAME: "execution-service"
